### ISSUE TITLE
toytree error

### ISSUE THREAD

**Issue by tangerzhang** [eaton-lab/toytree#11]
Hi,
I am running toytree to plot a gene network and I found error like this:
>>boots.draw_cloudtree()
(<toyplot.canvas.Canvas object at 0x10e779cd0>, <toyplot.coordinates.Cartesian object at 0x10e779d10>)

Does anyone know how to solve this problem?
Thanks

**Comment by eaton-lab** [comment]
Hi @tangerzhang , 

This is the way that toytree returns plotted objects, as a tuple that includes a Canvas object and a Cartesian axes object. It is not a warning or error message. This design comes from toyplot. If you are running your code in a notebook then the plot should display automatically in the output below your execution cell. There are two ways to suppress the statement showing the returned objects, shown below:

```python
## store the canvas and axes objects
canvas, axes = boots.draw_cloudtree()

## or, simply suppress the return statement with ';'
boots.draw_cloudtree();
```
