### ISSUE TITLE
Inconsistent tip color behavior

### ISSUE THREAD

**Issue by isgilman** [eaton-lab/toytree#16]
I'm really exited for a finally great way to plot trees in python. I'm not sure what's going on with the tip label coloring but when I run the modified example:

```python
import toytree as tt
import toyplot as tp

canvas = tp.Canvas(width='8in', height='2in')
ax0 = canvas.cartesian(bounds=('10%', '40%', '10%', '90%'))
ax1 = canvas.cartesian(bounds=('60%', '90%', '10%', '90%'))
## set a single tip labels color
tre.draw(tip_labels_color="darkcyan", axes=ax0);

## use a list of colors to assign different values to tips
colorlist = ["darkcyan" if "tom" in t else "darkorange" for t in tre.get_tip_labels()]
tre.draw(tip_labels_color=colorlist, axes=ax1);

ax0.show=False
ax1.show=False
```
I end up with "orange" and "pepper" in dark cyan. When I tried `if "apple" in t`... I get "eggplant" in dark cyan. 

toytree version: 0.1.6
toyplot version: 0.16.1

Thanks, Ian

**Comment by eaton-lab** [comment]
Hey Ian, 

Thanks, it's a fun project, but needs a lot of work still. It's definitely convenient to have a custom tree object that works the way we want for a lot of projects we're working on.

I think the order of colorlist is reversed right now. Probably a bug I introduced while trying to get things to work a certain way when the tree orientation is "down" versus "right". A hack fix for right now is to enter `tre.draw(tip_labels_color=colorlist[::-1], axes=ax1)`. But I agree its not intuitive and the `tip_labels_color` argument should just orient the list to be in the same order as `.get_tip_labels()` returns it.  

D

**Comment by isgilman** [comment]
That fixed it! Thank you

**Comment by eaton-lab** [comment]
Update: returns consistent behavior now.
