### ISSUE TITLE
help wanted: edge_label

### ISSUE THREAD

**Issue by zhh210** [eaton-lab/toytree#18]
Hello,

Thanks a lot for developing toytree! I'm wondering if it is possible to add label for edge as well? Any comment on which part of the code could be revised to add this feature is welcomed.

**Comment by eaton-lab** [comment]
You can find an example below, where node labels are shifted to edges using style options. I could imagine creating a dedicated function to place values on the midpoint of edges, but I haven't developed something like that yet.

https://toytree.readthedocs.io/en/latest/Cookbook.html#4.-Variable-edge-colors-and-widths
