### ISSUE TITLE
Test/Support Python 3+

### ISSUE THREAD

**Issue by eaton-lab** [eaton-lab/toytree#2]
TODO

**Comment by Zsailer** [comment]
Been using this in Python 3.6 for a little while. Haven't noticed any problems, yet.

Can we add Python 3 to the conda recipe? Currently, the recipe throws an error if you try to install in Python 3+, leading users to install from source.

**Comment by hmelberg** [comment]
I use the library with Python 3.6 and for the most part it works fine (Thank you!). However, there may be some issues sometimes. For instance, the use of `iteritems()` Below is the output I got after `tre = toyplot.rtree(ntips=10)`

> 
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-120-ee3172b7c718> in <module>()
> ----> 1 tre = tt.rtree(ntips=10)
> 
> ~\Anaconda3\lib\site-packages\toytree\tree.py in randomtree(ntips, node_values)
>     619 
>     620     ## set values
> --> 621     for fkey, vals in node_values.iteritems():
>     622         for idx, node in enumerate(self.tree.traverse()):
>     623             node.add_feature(fkey, vals[idx])
> 
> AttributeError: 'dict' object has no attribute 'iteritems'
> ----> 1 tre = tt.rtree(ntips=10)
> 
> ~\Anaconda3\lib\site-packages\toytree\tree.py in randomtree(ntips, node_values)
>     619 
>     620     ## set values
> --> 621     for fkey, vals in node_values.iteritems():
>     622         for idx, node in enumerate(self.tree.traverse()):
>     623             node.add_feature(fkey, vals[idx])
> 
> AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by eaton-lab** [comment]
OK, as of version 0.1.6 toytree should be fully Py3 compatible, finally. It is now passing all tests on builds, during which time it runs all code in the documentation notebooks for py27 and py36 on Linux and OSX. I'm gonna close this, but let me know if you run into any py3 compatibility errors. Thanks.
