### ISSUE TITLE
exporting trees from Toytree

### ISSUE THREAD

**Issue by Hazelhuangup** [eaton-lab/toytree#24]
Hi Dr Eaton, 

I am wondering if I am using python script, any way to export the tree object to SVG or pdf files? Tried pickle.dump but only with text as output.

Best regards,
Wu

**Comment by eaton-lab** [comment]
Yes, you can definitely save as SVG or PDF, see here: https://toytree.readthedocs.io/en/latest/4-tutorial.html#Drawing:-saving-figures
