### ISSUE TITLE
add matrix to tree view

### ISSUE THREAD

**Issue by phiweger** [eaton-lab/toytree#27]
hi, awesome library!

is it possible to place a feature matrix next to the tree, like the barplot in the tutorial?

kind regards

**Comment by eaton-lab** [comment]
Thanks @phiweger! I added a new section to the Cookbook gallery with some examples: https://toytree.readthedocs.io/en/latest/Cookbook.html#7.-Plot-tree-with-matrix/heatmap

**Comment by phiweger** [comment]
@eaton-lab thanks a lot! I have a question on this:

[here](https://toytree.readthedocs.io/en/latest/Cookbook.html#Method-1:) you show how to add a random matrix; but how to add tip-specific features?

for example, say I have a tree w/ 3 tips (A, B, C) and some features {A: 1, B: 3, C: 2.4} -- is there a way to add the matrix without "looping through the coordinates" and adding the features manually?
