### ISSUE TITLE
Toytree.prune()

### ISSUE THREAD

**Issue by isaacovercast** [eaton-lab/toytree#30]
The comment in the code of toytree.drop_tips() suggests to see .prune() if you want to _retain_ samples rather than drop, but toytree doesn't have this function, which is only present in treenode. Of course the functionality of prune can be implemented with drop_tips and a tiny bit of housekeeping.

A related issue is that the toytree object is careful about returning a copy when it is operated on, but this is not true of the treenode object, so calling treenode.prune() is destructive, and there's not a straightforward way to make a deep copy without actually using copy.deepcopy()

**Comment by eaton-lab** [comment]
Aha, I bet I planned to make a ToyTree function to `.prune()` and return a copy but then forgot. **TODO**.

Yeah, the destructive changes by treenode functions are dangerous. I think I say in the docs that users should probably stay away from them if they can. I think for power users it is useful to know that you can access those functions though.

**Comment by eaton-lab** [comment]
Now implemented.
Example: https://github.com/eaton-lab/toytree/blob/master/sandbox/30-add_prune_function.ipynb
