### ISSUE TITLE
Randomtree `random_names` isn't working

### ISSUE THREAD

**Issue by isaacovercast** [eaton-lab/toytree#39]
Looks like all the random tree functions got a `random_names` parameter, but it doesn't appear to be doing anything.
```
        nidx = list(range(tre.ntips))
        if random_names:
            random.shuffle(nidx)
        for idx, node in tre.idx_dict.items():
            if node.is_leaf():
                node.name = "r{}".format(nidx[idx])
```
The `nidx` list does get randomized, but it's never used to construct the names. You probably are aware of this already ;)

**Comment by eaton-lab** [comment]
Fixed: https://github.com/eaton-lab/toytree/blob/master/sandbox/39-randomtrees-randomnames.ipynb
