### ISSUE TITLE
Question about inner node labels position

### ISSUE THREAD

**Issue by Tdanis** [eaton-lab/toytree#42]
Hello,

I am a new user of toytree tool, could you tell me please how can I change the position of inner nodes added custom labels. For examble I want to plot some new_added features above or below or right the branches . Could you  help me with this please?

Thank you,
Thodoris

**Comment by eaton-lab** [comment]
Hi @Tdanis  

Please see the documentation for instructions on styling tree drawings. In addition, this notebook provides some tips for your specific question: https://github.com/eaton-lab/toytree/blob/master/sandbox/42-custom-inner-node-labels.ipynb
