### ISSUE TITLE
ts='p' plotting bug

### ISSUE THREAD

**Issue by pmckenz1** [eaton-lab/toytree#49]
When drawing in a notebook with ts='p', trees are plotting strangely with respect to the axes -- example below.

<img width="366" alt="Screen Shot 2021-02-10 at 11 54 35 PM" src="https://user-images.githubusercontent.com/18040177/107603666-793df900-6bfb-11eb-94cb-f7b304d9603b.png">

**Comment by eaton-lab** [comment]
Thanks. Bug was in master but not main version. Fixed in next release.
