### ISSUE TITLE
cannot generate italic labels

### ISSUE THREAD

**Issue by Jiung-Wen** [eaton-lab/toytree#52]
Hi,

Thanks for the amazing tool! I was using the latest version (v2.0.5) but I found that the italic labels cannot be generated even the <i></i> tags were added. This script was directly copy from [the official document](https://toytree.readthedocs.io/en/latest/8-styling.html#tip_labels). Thank you.

Best,
Jiung-Wen

<img width="721" alt="Screen Shot 2021-07-19 at 3 05 03 PM" src="https://user-images.githubusercontent.com/30737103/126220963-b024df37-315f-483d-bc5e-e5f5f6622e34.png">

**Comment by eaton-lab** [comment]
Thanks @Jiung-Wen , 

I found the bug and fixed it. This will work in the next versioned update.

**Comment by StuntsPT** [comment]
Hi @eaton-lab ,
I'm requesting a reopen, since this issue seems to persist (or maybe it's back?) at least as of 9d706e7.
