### ISSUE TITLE
lift numpy version ceiling?

### ISSUE THREAD

**Issue by ryneches** [eaton-lab/toytree#98]
Hey! Is there still a reason to require numpy >= 2.0.0? I tried flipping this to numpy <= 2.0.0, ran the tests, built some trees, and everything seems OK. Obviously that's not particularly rigorous. What was the reason for the version ceiling?

**Comment by eaton-lab** [comment]
Oh, you're right. I was waiting for an update to toyplot, which has been released since September. I will update the conda and pip dependencies.
